w7d2/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]
  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, except: [:new, :index] do
    resources :tracks, only: [:new]
  end
  resources :tracks, except: [:new, :index] do
    resources :notes, only: [:create, :destroy]
  end
end

w7d2/music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :albums,
    dependent: :destroy

  has_many :tracks,
    through: :albums,
    source: :tracks,
    dependent: :destroy
  
end

w7d2/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

w7d2/music_app/app/helpers/bands_helper.rb
module BandsHelper
end

w7d2/music_app/app/views/bands/edit.html.erb
<h1>Edit Band</h1>

<form action=<%= band_url(@band) %> method = "post">
    <input type="hidden" name="_method" value="patch">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"> 
    <label>Band Name
    <input type="text" name="band[name]" value=<%= @band.name %>>
    </label>
    <input type="submit" value="Submit">

</form>

w7d2/music_app/app/views/bands/index.html.erb
<h1>All Bands</h1>

<ul>
<% @bands.each do |band|%>
    <li><%= band.name %></li>
<% end %>
</ul>

w7d2/music_app/app/views/bands/new.html.erb
<h1>Create Band</h1>

<form action=<%= bands_url %> method = "post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"> 
    <label>Band Name
    <input type="text" name="band[name]" value=<%= @band.name %>>
    </label>
    <input type="submit" value="Submit">

</form>

w7d2/music_app/app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<ul>
    <% @band.albums.each do |album| %>
        <a href=<%= album_url(album) %>><%= album.title %></a>
    <% end %>
</ul>