w7d2/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]
  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, except: [:new, :index] do
    resources :tracks, only: [:new]
  end
  resources :tracks, except: [:new, :index] do
    resources :notes, only: [:create, :destroy]
  end
end

w7d2/music_app/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  year       :integer          not null
#  band_id    :integer          not null
#  is_live    :boolean          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Album < ApplicationRecord
  validates :title, :year, :is_live, :band_id, presence: true
  validates :title, uniqueness: {scope: :band_id}
  validates :is_live, inclusion: [true, false]

  belongs_to :band
  has_many :tracks,
    dependent: :destroy
  

end

w7d2/music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def new
    @album = Album.new({band_id: params[:band_id]})
    # @album.band_id = params[:band_id]
    render :new
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def create
    # debugger
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to bands_url
  end
  private
  def album_params
    params.require(:album).permit(:band_id, :is_live, :title, :year)
  end
end

w7d2/music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

w7d2/music_app/app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<form action=<%= album_url(@album) %> method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token%>>
  <label>Title
    <input type="text" name="album[title]" value=<%= @album.title %>>
  </label>
  <label>Year
    <input type="text" name="album[year]" value=<%= @album.year %>>
  </label>
  <label>Live
    <input type="radio" name="album[is_live]" value="true" <%= @album.is_live == true ? "checked" : "" %>>
  </label>
  <label>Studio
    <input type="radio" name="album[is_live]" value="false" <%= !@album.is_live == false ? "checked" : "" %>>
  </label>
  <label>Band
    <select name="album[band_id]">
      <% Band.all.each do |band| %>
        <option value=<%= band.id %> <%= band.id == params[:band_id] ? "selected" : "" %>  ><%= band.name %></option>
      <% end %>
    </select>
  </label>
  <input type="submit" value="Submit">
</form>

w7d2/music_app/app/views/albums/new.html.erb
<h1>New Album </h1>

<form action=<%= albums_url %> method="post">
  <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token%>>
  <label>Title
    <input type="text" name="album[title]" value=<%= @album.title %>>
  </label>
  <label>Year
    <input type="text" name="album[year]" value=<%= @album.year %>>
  </label>
  
  <label>Live
    <input type="radio" name="album[is_live]" value="true" <%= @album.is_live == true ? "checked" : "" %>>
  </label>
  <label>Studio
    <input type="radio" name="album[is_live]" value="false" <%= !@album.is_live == false ? "checked" : "" %>>
  </label>

  <label>Band
    <select name="album[band_id]">
      <% Band.all.each do |band| %>
        <option value=<%= band.id %> <%= band.id == params[:band_id] ? "selected" : "" %>  ><%= band.name %></option>
      <% end %>
    </select>
  </label>

  <input type="submit" value="Submit">
</form>

w7d2/music_app/app/views/albums/show.html.erb
<h1><%= @album.title %></h1>

<a href=<%= band_url(@album.band_id) %>><%= @album.band.name %></a> 
<a href=<%= edit_album_url(@album) %>>Edit Album</a>

<form action=<%= album_url %> method="post">
    <input type="hidden" name="_method" value="delete">
    <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %>>

    <input type="submit" value="Delete Album">
</form>


<ul>
    <% @album.tracks.each do |track| %>
        <a href=<%= track_url(track) %>><%= track.title %></a>
    <% end %>
</ul>

<a href=<%= new_album_track_url(@album) %>>Add Track</a>